server:
  port: ${global.gather.server.port}
spring:
  profiles:
    include: global
  application:
    name: metadata-gather
  datasource:
    name: ${global.datasource.name}
    url: jdbc:mysql://${global.datasource.url}:${global.datasource.port}/${global.datasource.database-name}?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${global.datasource.username}
    password: ${global.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      log-abandoned: true
  flyway:
    locations: classpath:migration
    enabled: false
  jooq:
    sql-dialect: MYSQL
  main:
    allow-bean-definition-overriding: true
logging:
  gather:
    storage: ${global.gather.logger.storage}
    path: ${global.gather.logger.path}
  level:
    root: info

