server:
  port: ${global.target.server.port}
spring:
  resources:
    static-locations: classpath:/webapp/
  datasource:
    logAbandoned: true
    minIdle: 5
    removeAbandoned: true
    maxWait: 1000
    name: kylo
    removeAbandonedTimeout: 60
    url: jdbc:mysql://127.0.0.1:3306/kylo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:migration
    enabled: false
  jooq:
    sql-dialect: MYSQL
  profiles:
    include: global

logging:
  level:
    root: info

azkaban:
  url: http://192.168.23.226:8081
  username: azkaban
  password: azkaban
  execute:
    path: /opt/app/azkaban/urule-azkaban-executor
